version: '3.8'

services:
  psql:
    image: postgres:latest
    healthcheck: 
      test: ["CMD-SHELL", "sh -c pg_isready '-U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    networks:
      - default
  app:
    depends_on: 
      psql:
          condition: service_healthy
    build:
      context: .
      target: dev
    env_file: .env
    ports:
      - "3001:3001"
      - "2345:2345"
    volumes:
      - ./:/app:rw,delegated
    tty: true
    stdin_open: true
    networks:
      - default
    

volumes:
  psql_volume:
networks:
  default: {}
