services:
  psql:
    image: postgres:latest
    healthcheck: 
      test: ["CMD-SHELL", "sh -c pg_isready '-U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file: 
      - path: ./.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    networks:
      - default

  migrations:
    image: arigaio/atlas:latest
    command: >
      migrate apply
      --url postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?sslmode=disable
    env_file: 
      - path: ./.env
    networks:
      - default
    depends_on: 
      psql:
        condition: service_healthy
    volumes:
      - ./internal/database/migrations/:/migrations

  app:
    depends_on:
      - migrations
    build:
      context: .
      target: dev
    env_file: 
      - path: ./.env
    ports:
      - "3001:3001"
      - "2345:2345"
    volumes:
      - ./:/app:rw,delegated
    tty: true
    stdin_open: true
    networks:
      - default
    

volumes:
  psql_volume:
networks:
  default: {}
