/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyActivityDifficultyTier : An enumeration representing the potential difficulty levels of an activity. Their names are... more qualitative than quantitative.
type DestinyDestinyActivityDifficultyTier int32

// List of Destiny.DestinyActivityDifficultyTier
const (
	0__DestinyDestinyActivityDifficultyTier DestinyDestinyActivityDifficultyTier = "0"
	1__DestinyDestinyActivityDifficultyTier DestinyDestinyActivityDifficultyTier = "1"
	2__DestinyDestinyActivityDifficultyTier DestinyDestinyActivityDifficultyTier = "2"
	3__DestinyDestinyActivityDifficultyTier DestinyDestinyActivityDifficultyTier = "3"
	4__DestinyDestinyActivityDifficultyTier DestinyDestinyActivityDifficultyTier = "4"
	5__DestinyDestinyActivityDifficultyTier DestinyDestinyActivityDifficultyTier = "5"
	6__DestinyDestinyActivityDifficultyTier DestinyDestinyActivityDifficultyTier = "6"
	7__DestinyDestinyActivityDifficultyTier DestinyDestinyActivityDifficultyTier = "7"
)
