/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// These definitions represent Factions in the game. Factions have ended up unilaterally being related to Vendors that represent them, but that need not necessarily be the case.  A Faction is really just an entity that has a related progression for which a character can gain experience. In Destiny 1, Dead Orbit was an example of a Faction: there happens to be a Vendor that represents Dead Orbit (and indeed, DestinyVendorDefinition.factionHash defines to this relationship), but Dead Orbit could theoretically exist without the Vendor that provides rewards.
type DestinyDefinitionsDestinyFactionDefinition struct {
	DisplayProperties *DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition `json:"displayProperties,omitempty"`
	// The hash identifier for the DestinyProgressionDefinition that indicates the character's relationship with this faction in terms of experience and levels.
	ProgressionHash int32 `json:"progressionHash,omitempty"`
	// The faction token item hashes, and their respective progression values.
	TokenValues map[string]int32 `json:"tokenValues,omitempty"`
	// The faction reward item hash, usually an engram.
	RewardItemHash int32 `json:"rewardItemHash,omitempty"`
	// The faction reward vendor hash, used for faction engram previews.
	RewardVendorHash int32 `json:"rewardVendorHash,omitempty"`
	// List of vendors that are associated with this faction. The last vendor that passes the unlock flag checks is the one that should be shown.
	Vendors []DestinyDefinitionsDestinyFactionVendorDefinition `json:"vendors,omitempty"`
	// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
	Hash int32 `json:"hash,omitempty"`
	// The index of the entity as it was found in the investment tables.
	Index int32 `json:"index,omitempty"`
	// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
	Redacted bool `json:"redacted,omitempty"`
}
