/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ApplicationsDeveloperRole int32

// List of Applications.DeveloperRole
const (
	_0__ApplicationsDeveloperRole ApplicationsDeveloperRole = 0
	_1__ApplicationsDeveloperRole ApplicationsDeveloperRole = 1
	_2__ApplicationsDeveloperRole ApplicationsDeveloperRole = 2
)
