/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyVendorItemStatus int32

// List of Destiny.VendorItemStatus
const (
	0__DestinyVendorItemStatus DestinyVendorItemStatus = "0"
	1__DestinyVendorItemStatus DestinyVendorItemStatus = "1"
	2__DestinyVendorItemStatus DestinyVendorItemStatus = "2"
	4__DestinyVendorItemStatus DestinyVendorItemStatus = "4"
	8__DestinyVendorItemStatus DestinyVendorItemStatus = "8"
	16__DestinyVendorItemStatus DestinyVendorItemStatus = "16"
	32__DestinyVendorItemStatus DestinyVendorItemStatus = "32"
	64__DestinyVendorItemStatus DestinyVendorItemStatus = "64"
	128__DestinyVendorItemStatus DestinyVendorItemStatus = "128"
	256__DestinyVendorItemStatus DestinyVendorItemStatus = "256"
	512__DestinyVendorItemStatus DestinyVendorItemStatus = "512"
	1024__DestinyVendorItemStatus DestinyVendorItemStatus = "1024"
	2048__DestinyVendorItemStatus DestinyVendorItemStatus = "2048"
	4096__DestinyVendorItemStatus DestinyVendorItemStatus = "4096"
	8192__DestinyVendorItemStatus DestinyVendorItemStatus = "8192"
)
