/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Data about an item's \"sources\": ways that the item can be obtained.
type DestinyDefinitionsDestinyItemSourceBlockDefinition struct {
	// The list of hash identifiers for Reward Sources that hint where the item can be found (DestinyRewardSourceDefinition).
	SourceHashes []int32 `json:"sourceHashes,omitempty"`
	// A collection of details about the stats that were computed for the ways we found that the item could be spawned.
	Sources []DestinyDefinitionsSourcesDestinyItemSourceDefinition `json:"sources,omitempty"`
	// If we found that this item is exclusive to a specific platform, this will be set to the BungieMembershipType enumeration that matches that platform.
	Exclusive int32 `json:"exclusive,omitempty"`
	// A denormalized reference back to vendors that potentially sell this item.
	VendorSources []DestinyDefinitionsDestinyItemVendorSourceReference `json:"vendorSources,omitempty"`
}
