/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type FireteamFireteamPlatform int32

// List of Fireteam.FireteamPlatform
const (
	0__FireteamFireteamPlatform FireteamFireteamPlatform = "0"
	1__FireteamFireteamPlatform FireteamFireteamPlatform = "1"
	2__FireteamFireteamPlatform FireteamFireteamPlatform = "2"
	3__FireteamFireteamPlatform FireteamFireteamPlatform = "3"
	4__FireteamFireteamPlatform FireteamFireteamPlatform = "4"
	5__FireteamFireteamPlatform FireteamFireteamPlatform = "5"
	6__FireteamFireteamPlatform FireteamFireteamPlatform = "6"
)
