/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type TrendingTrendingEntryCommunityCreation struct {
	Media string `json:"media,omitempty"`
	Title string `json:"title,omitempty"`
	Author string `json:"author,omitempty"`
	AuthorMembershipId int64 `json:"authorMembershipId,omitempty"`
	PostId int64 `json:"postId,omitempty"`
	Body string `json:"body,omitempty"`
	Upvotes int32 `json:"upvotes,omitempty"`
}
