/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyHistoricalStatsDefinitionsPeriodType int32

// List of Destiny.HistoricalStats.Definitions.PeriodType
const (
	0__DestinyHistoricalStatsDefinitionsPeriodType DestinyHistoricalStatsDefinitionsPeriodType = "0"
	1__DestinyHistoricalStatsDefinitionsPeriodType DestinyHistoricalStatsDefinitionsPeriodType = "1"
	2__DestinyHistoricalStatsDefinitionsPeriodType DestinyHistoricalStatsDefinitionsPeriodType = "2"
	3__DestinyHistoricalStatsDefinitionsPeriodType DestinyHistoricalStatsDefinitionsPeriodType = "3"
)
