/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// GroupsV2HostGuidedGamesPermissionLevel : Used for setting the guided game permission level override (admins and founders can always host guided games).
type GroupsV2HostGuidedGamesPermissionLevel int32

// List of GroupsV2.HostGuidedGamesPermissionLevel
const (
	_0__GroupsV2HostGuidedGamesPermissionLevel GroupsV2HostGuidedGamesPermissionLevel = 0
	_1__GroupsV2HostGuidedGamesPermissionLevel GroupsV2HostGuidedGamesPermissionLevel = 1
	_2__GroupsV2HostGuidedGamesPermissionLevel GroupsV2HostGuidedGamesPermissionLevel = 2
)
