/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ForumsForumFlagsEnum int32

// List of Forums.ForumFlagsEnum
const (
	0__ForumsForumFlagsEnum ForumsForumFlagsEnum = "0"
	1__ForumsForumFlagsEnum ForumsForumFlagsEnum = "1"
	2__ForumsForumFlagsEnum ForumsForumFlagsEnum = "2"
	4__ForumsForumFlagsEnum ForumsForumFlagsEnum = "4"
	8__ForumsForumFlagsEnum ForumsForumFlagsEnum = "8"
	16__ForumsForumFlagsEnum ForumsForumFlagsEnum = "16"
	32__ForumsForumFlagsEnum ForumsForumFlagsEnum = "32"
	64__ForumsForumFlagsEnum ForumsForumFlagsEnum = "64"
	128__ForumsForumFlagsEnum ForumsForumFlagsEnum = "128"
)
