/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Do you ever get the feeling that a system has become so overburdened by edge cases that it probably should have become some other system entirely? So do I!  In totally unrelated news, Plugs can now override properties of their parent items. This is some of the relevant definition data for those overrides.  If this is populated, it will have the override data to be applied when this plug is applied to an item.
type AllOfDestinyDefinitionsItemsDestinyItemPlugDefinitionParentItemOverride struct {
	AdditionalEquipRequirementsDisplayStrings []string `json:"additionalEquipRequirementsDisplayStrings,omitempty"`
	PipIcon string `json:"pipIcon,omitempty"`
}
