/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// The #RGB string value for the color related to this progression, if there is one.
type AllOfDestinyDefinitionsDestinyProgressionDefinitionColor struct {
	Red string `json:"red,omitempty"`
	Green string `json:"green,omitempty"`
	Blue string `json:"blue,omitempty"`
	Alpha string `json:"alpha,omitempty"`
}
