/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyComponentsSocialDestinySocialCommendationsComponent struct {
	TotalScore int32 `json:"totalScore,omitempty"`
	ScoreDetailValues []int32 `json:"scoreDetailValues,omitempty"`
	CommendationNodeScoresByHash map[string]int32 `json:"commendationNodeScoresByHash,omitempty"`
	CommendationScoresByHash map[string]int32 `json:"commendationScoresByHash,omitempty"`
}
