/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Sometimes, an item will have a background color. Most notably this occurs with Emblems, who use the Background Color for small character nameplates such as the \"friends\" view you see in-game. There are almost certainly other items that have background color as well, though I have not bothered to investigate what items have it nor what purposes they serve: use it as you will.
type AllOfDestinyDefinitionsDestinyInventoryItemDefinitionBackgroundColor struct {
	Red string `json:"red,omitempty"`
	Green string `json:"green,omitempty"`
	Blue string `json:"blue,omitempty"`
	Alpha string `json:"alpha,omitempty"`
}
