/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type IgnoresIgnoreLength int32

// List of Ignores.IgnoreLength
const (
	_0__IgnoresIgnoreLength IgnoresIgnoreLength = 0
	_1__IgnoresIgnoreLength IgnoresIgnoreLength = 1
	_2__IgnoresIgnoreLength IgnoresIgnoreLength = 2
	_3__IgnoresIgnoreLength IgnoresIgnoreLength = 3
	_4__IgnoresIgnoreLength IgnoresIgnoreLength = 4
	_5__IgnoresIgnoreLength IgnoresIgnoreLength = 5
	_6__IgnoresIgnoreLength IgnoresIgnoreLength = 6
	_7__IgnoresIgnoreLength IgnoresIgnoreLength = 7
	_8__IgnoresIgnoreLength IgnoresIgnoreLength = 8
	_9__IgnoresIgnoreLength IgnoresIgnoreLength = 9
	_10__IgnoresIgnoreLength IgnoresIgnoreLength = 10
	_11__IgnoresIgnoreLength IgnoresIgnoreLength = 11
)
