/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes int32

// List of Destiny.Definitions.DestinyTalentNodeStepGuardianAttributes
const (
	0__DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "0"
	1__DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "1"
	2__DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "2"
	4__DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "4"
	8__DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "8"
	16__DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "16"
	32__DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "32"
	64__DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "64"
	128__DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "128"
	255__DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "255"
)
