/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyRequestsActionsDestinyItemStateRequest struct {
	State bool `json:"state,omitempty"`
	// The instance ID of the item for this action request.
	ItemId int64 `json:"itemId,omitempty"`
	CharacterId int64 `json:"characterId,omitempty"`
	MembershipType int32 `json:"membershipType,omitempty"`
}
