/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// A milestone need not have an active activity, but if there is one it will be returned here, along with any variant and additional information.
type AllOfDestinyMilestonesDestinyPublicMilestoneQuestActivity struct {
	// The hash identifier of the activity that's been chosen to be considered the canonical \"conceptual\" activity definition. This may have many variants, defined herein.
	ActivityHash int32 `json:"activityHash,omitempty"`
	// The activity may have 0-to-many modifiers: if it does, this will contain the hashes to the DestinyActivityModifierDefinition that defines the modifier being applied.
	ModifierHashes []int32 `json:"modifierHashes,omitempty"`
	// Every relevant variation of this conceptual activity, including the conceptual activity itself, have variants defined here.
	Variants []DestinyMilestonesDestinyPublicMilestoneActivityVariant `json:"variants,omitempty"`
	// The hash identifier of the most specific Activity Mode under which this activity is played. This is useful for situations where the activity in question is - for instance - a PVP map, but it's not clear what mode the PVP map is being played under. If it's a playlist, this will be less specific: but hopefully useful in some way.
	ActivityModeHash int32 `json:"activityModeHash,omitempty"`
	// The enumeration equivalent of the most specific Activity Mode under which this activity is played.
	ActivityModeType int32 `json:"activityModeType,omitempty"`
}
