/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyObjectiveGrantStyle : Some Objectives provide perks, generally as part of providing some kind of interesting modifier for a Challenge or Quest. This indicates when the Perk is granted.
type DestinyDestinyObjectiveGrantStyle int32

// List of Destiny.DestinyObjectiveGrantStyle
const (
	_0__DestinyDestinyObjectiveGrantStyle DestinyDestinyObjectiveGrantStyle = 0
	_1__DestinyDestinyObjectiveGrantStyle DestinyDestinyObjectiveGrantStyle = 1
	_2__DestinyDestinyObjectiveGrantStyle DestinyDestinyObjectiveGrantStyle = 2
)
