/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinySocketCategoryStyle : Represents the possible and known UI styles used by the game for rendering Socket Categories.
type DestinyDestinySocketCategoryStyle int32

// List of Destiny.DestinySocketCategoryStyle
const (
	0__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = "0"
	1__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = "1"
	2__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = "2"
	3__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = "3"
	4__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = "4"
	5__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = "5"
	6__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = "6"
	7__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = "7"
	8__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = "8"
)
