/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyConfigImagePyramidEntry struct {
	// The name of the subfolder where these images are located.
	Name string `json:"name,omitempty"`
	// The factor by which the original image size has been reduced.
	Factor float32 `json:"factor,omitempty"`
}
