/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyProgressionRewardItemState : Represents the different states a progression reward item can be in.
type DestinyDestinyProgressionRewardItemState int32

// List of Destiny.DestinyProgressionRewardItemState
const (
	_0__DestinyDestinyProgressionRewardItemState DestinyDestinyProgressionRewardItemState = 0
	_1__DestinyDestinyProgressionRewardItemState DestinyDestinyProgressionRewardItemState = 1
	_2__DestinyDestinyProgressionRewardItemState DestinyDestinyProgressionRewardItemState = 2
	_4__DestinyDestinyProgressionRewardItemState DestinyDestinyProgressionRewardItemState = 4
	_8__DestinyDestinyProgressionRewardItemState DestinyDestinyProgressionRewardItemState = 8
)
