/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// The child entities contained by this presentation node.
type AllOfDestinyDefinitionsPresentationDestinyPresentationNodeDefinitionChildren struct {
	PresentationNodes []DestinyDefinitionsPresentationDestinyPresentationNodeChildEntry `json:"presentationNodes,omitempty"`
	Collectibles []DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry `json:"collectibles,omitempty"`
	Records []DestinyDefinitionsPresentationDestinyPresentationNodeRecordChildEntry `json:"records,omitempty"`
	Metrics []DestinyDefinitionsPresentationDestinyPresentationNodeMetricChildEntry `json:"metrics,omitempty"`
	Craftables []DestinyDefinitionsPresentationDestinyPresentationNodeCraftableChildEntry `json:"craftables,omitempty"`
}
