/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// This is the silver available on this Profile across any platforms on which they have purchased silver.   This is only available if you are requesting yourself.
type AllOfDestinyResponsesDestinyProfileUserInfoCardPlatformSilver struct {
	// If a Profile is played on multiple platforms, this is the silver they have for each platform, keyed by Membership Type.
	PlatformSilver map[string]DestinyEntitiesItemsDestinyItemComponent `json:"platformSilver,omitempty"`
}
