/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
D2Client
// TrendingTrendingEntryType : The known entity types that you can have returned from Trending.
type TrendingTrendingEntryType int32

// List of Trending.TrendingEntryType
const (
	0__TrendingTrendingEntryType TrendingTrendingEntryType = "0"
	1__TrendingTrendingEntryType TrendingTrendingEntryType = "1"
	2__TrendingTrendingEntryType TrendingTrendingEntryType = "2"
	3__TrendingTrendingEntryType TrendingTrendingEntryType = "3"
	4__TrendingTrendingEntryType TrendingTrendingEntryType = "4"
	5__TrendingTrendingEntryType TrendingTrendingEntryType = "5"
	6__TrendingTrendingEntryType TrendingTrendingEntryType = "6"
	7__TrendingTrendingEntryType TrendingTrendingEntryType = "7"
	8__TrendingTrendingEntryType TrendingTrendingEntryType = "8"
	9__TrendingTrendingEntryType TrendingTrendingEntryType = "9"
	10__TrendingTrendingEntryType TrendingTrendingEntryType = "10"
	11__TrendingTrendingEntryType TrendingTrendingEntryType = "11"
)
