/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyVendorDisplayCategorySortOrder : Display categories can have custom sort orders. These are the possible options.
type DestinyVendorDisplayCategorySortOrder int32

// List of Destiny.VendorDisplayCategorySortOrder
const (
	0__DestinyVendorDisplayCategorySortOrder DestinyVendorDisplayCategorySortOrder = "0"
	1__DestinyVendorDisplayCategorySortOrder DestinyVendorDisplayCategorySortOrder = "1"
)
