/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// The metrics available for display and selection on an item.
type DestinyDefinitionsDestinyItemMetricBlockDefinition struct {
	// Hash identifiers for any DestinyPresentationNodeDefinition entry that can be used to list available metrics. Any metric listed directly below these nodes, or in any of these nodes' children will be made available for selection.
	AvailableMetricCategoryNodeHashes []int32 `json:"availableMetricCategoryNodeHashes,omitempty"`
}
