/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyVendorInteractionType : An enumeration of the known UI interactions for Vendors.
type DestinyVendorInteractionType int32

// List of Destiny.VendorInteractionType
const (
	0__DestinyVendorInteractionType DestinyVendorInteractionType = "0"
	1__DestinyVendorInteractionType DestinyVendorInteractionType = "1"
	2__DestinyVendorInteractionType DestinyVendorInteractionType = "2"
	3__DestinyVendorInteractionType DestinyVendorInteractionType = "3"
	4__DestinyVendorInteractionType DestinyVendorInteractionType = "4"
	5__DestinyVendorInteractionType DestinyVendorInteractionType = "5"
	6__DestinyVendorInteractionType DestinyVendorInteractionType = "6"
	7__DestinyVendorInteractionType DestinyVendorInteractionType = "7"
	8__DestinyVendorInteractionType DestinyVendorInteractionType = "8"
	9__DestinyVendorInteractionType DestinyVendorInteractionType = "9"
	10__DestinyVendorInteractionType DestinyVendorInteractionType = "10"
)
