/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyJoinClosedReasons : A Flags enumeration representing the reasons why a person can't join this user's fireteam.
type DestinyDestinyJoinClosedReasons int32

// List of Destiny.DestinyJoinClosedReasons
const (
	0__DestinyDestinyJoinClosedReasons DestinyDestinyJoinClosedReasons = "0"
	1__DestinyDestinyJoinClosedReasons DestinyDestinyJoinClosedReasons = "1"
	2__DestinyDestinyJoinClosedReasons DestinyDestinyJoinClosedReasons = "2"
	4__DestinyDestinyJoinClosedReasons DestinyDestinyJoinClosedReasons = "4"
	8__DestinyDestinyJoinClosedReasons DestinyDestinyJoinClosedReasons = "8"
	16__DestinyDestinyJoinClosedReasons DestinyDestinyJoinClosedReasons = "16"
	32768__DestinyDestinyJoinClosedReasons DestinyDestinyJoinClosedReasons = "32768"
)
