/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type GroupsV2GroupPostPublicity int32

// List of GroupsV2.GroupPostPublicity
const (
	0__GroupsV2GroupPostPublicity GroupsV2GroupPostPublicity = "0"
	1__GroupsV2GroupPostPublicity GroupsV2GroupPostPublicity = "1"
	2__GroupsV2GroupPostPublicity GroupsV2GroupPostPublicity = "2"
)
