/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type FireteamFireteamSlotSearch int32

// List of Fireteam.FireteamSlotSearch
const (
	0__FireteamFireteamSlotSearch FireteamFireteamSlotSearch = "0"
	1__FireteamFireteamSlotSearch FireteamFireteamSlotSearch = "1"
	2__FireteamFireteamSlotSearch FireteamFireteamSlotSearch = "2"
)
