/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ForumForumTopicsSortEnum int32

// List of Forum.ForumTopicsSortEnum
const (
	_0__ForumForumTopicsSortEnum ForumForumTopicsSortEnum = 0
	_1__ForumForumTopicsSortEnum ForumForumTopicsSortEnum = 1
	_2__ForumForumTopicsSortEnum ForumForumTopicsSortEnum = 2
	_3__ForumForumTopicsSortEnum ForumForumTopicsSortEnum = 3
	_4__ForumForumTopicsSortEnum ForumForumTopicsSortEnum = 4
	_5__ForumForumTopicsSortEnum ForumForumTopicsSortEnum = 5
	_6__ForumForumTopicsSortEnum ForumForumTopicsSortEnum = 6
	_7__ForumForumTopicsSortEnum ForumForumTopicsSortEnum = 7
)
