/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyPresentationDisplayStyle : A hint for how the presentation node should be displayed when shown in a list. How you use this is your UI is up to you.
type DestinyDestinyPresentationDisplayStyle int32

// List of Destiny.DestinyPresentationDisplayStyle
const (
	_0__DestinyDestinyPresentationDisplayStyle DestinyDestinyPresentationDisplayStyle = 0
	_1__DestinyDestinyPresentationDisplayStyle DestinyDestinyPresentationDisplayStyle = 1
	_2__DestinyDestinyPresentationDisplayStyle DestinyDestinyPresentationDisplayStyle = 2
	_3__DestinyDestinyPresentationDisplayStyle DestinyDestinyPresentationDisplayStyle = 3
	_4__DestinyDestinyPresentationDisplayStyle DestinyDestinyPresentationDisplayStyle = 4
	_5__DestinyDestinyPresentationDisplayStyle DestinyDestinyPresentationDisplayStyle = 5
	_6__DestinyDestinyPresentationDisplayStyle DestinyDestinyPresentationDisplayStyle = 6
)
