/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type StreamingDropStateEnum int32

// List of Streaming.DropStateEnum
const (
	_0__StreamingDropStateEnum StreamingDropStateEnum = 0
	_1__StreamingDropStateEnum StreamingDropStateEnum = 1
	_2__StreamingDropStateEnum StreamingDropStateEnum = 2
)
