/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ForumForumTopicsQuickDateEnum int32

// List of Forum.ForumTopicsQuickDateEnum
const (
	0__ForumForumTopicsQuickDateEnum ForumForumTopicsQuickDateEnum = "0"
	1__ForumForumTopicsQuickDateEnum ForumForumTopicsQuickDateEnum = "1"
	2__ForumForumTopicsQuickDateEnum ForumForumTopicsQuickDateEnum = "2"
	3__ForumForumTopicsQuickDateEnum ForumForumTopicsQuickDateEnum = "3"
	4__ForumForumTopicsQuickDateEnum ForumForumTopicsQuickDateEnum = "4"
)
