/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDefinitionsMilestonesDestinyMilestoneDisplayPreference : A hint for the UI as to what display information ought to be shown. Defaults to showing the static MilestoneDefinition's display properties.   If for some reason the indicated property is not populated, fall back to the MilestoneDefinition.displayProperties.
type DestinyDefinitionsMilestonesDestinyMilestoneDisplayPreference int32

// List of Destiny.Definitions.Milestones.DestinyMilestoneDisplayPreference
const (
	_0__DestinyDefinitionsMilestonesDestinyMilestoneDisplayPreference DestinyDefinitionsMilestonesDestinyMilestoneDisplayPreference = 0
	_1__DestinyDefinitionsMilestonesDestinyMilestoneDisplayPreference DestinyDefinitionsMilestonesDestinyMilestoneDisplayPreference = 1
	_2__DestinyDefinitionsMilestonesDestinyMilestoneDisplayPreference DestinyDefinitionsMilestonesDestinyMilestoneDisplayPreference = 2
)
