/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinySpecialItemType : As you run into items that need to be classified for Milestone purposes in ways that we cannot infer via direct data, add a new classification here and use a string constant to represent it in the local item config file.  NOTE: This is not all of the item types available, and some of these are holdovers from Destiny 1 that may or may not still exist.
type DestinySpecialItemType int32

// List of Destiny.SpecialItemType
const (
	_0__DestinySpecialItemType DestinySpecialItemType = 0
	_1__DestinySpecialItemType DestinySpecialItemType = 1
	_8__DestinySpecialItemType DestinySpecialItemType = 8
	_9__DestinySpecialItemType DestinySpecialItemType = 9
	_23__DestinySpecialItemType DestinySpecialItemType = 23
	_24__DestinySpecialItemType DestinySpecialItemType = 24
	_25__DestinySpecialItemType DestinySpecialItemType = 25
	_27__DestinySpecialItemType DestinySpecialItemType = 27
	_29__DestinySpecialItemType DestinySpecialItemType = 29
)
