/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type GroupsV2GroupSortBy int32

// List of GroupsV2.GroupSortBy
const (
	0__GroupsV2GroupSortBy GroupsV2GroupSortBy = "0"
	1__GroupsV2GroupSortBy GroupsV2GroupSortBy = "1"
	2__GroupsV2GroupSortBy GroupsV2GroupSortBy = "2"
	3__GroupsV2GroupSortBy GroupsV2GroupSortBy = "3"
)
