/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyComponentsRecordsDestinyProfileRecordsComponent struct {
	// Your 'active' Triumphs score, maintained for backwards compatibility.
	Score int32 `json:"score,omitempty"`
	// Your 'active' Triumphs score.
	ActiveScore int32 `json:"activeScore,omitempty"`
	// Your 'legacy' Triumphs score.
	LegacyScore int32 `json:"legacyScore,omitempty"`
	// Your 'lifetime' Triumphs score.
	LifetimeScore int32 `json:"lifetimeScore,omitempty"`
	// If this profile is tracking a record, this is the hash identifier of the record it is tracking.
	TrackedRecordHash int32 `json:"trackedRecordHash,omitempty"`
	Records map[string]DestinyComponentsRecordsDestinyRecordComponent `json:"records,omitempty"`
	// The hash for the root presentation node definition of Triumph categories.
	RecordCategoriesRootNodeHash int32 `json:"recordCategoriesRootNodeHash,omitempty"`
	// The hash for the root presentation node definition of Triumph Seals.
	RecordSealsRootNodeHash int32 `json:"recordSealsRootNodeHash,omitempty"`
}
