/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyUnlockValueUiStyle : If you're showing an unlock value in the UI, this is the format in which it should be shown. You'll have to build your own algorithms on the client side to determine how best to render these options.
type DestinyDestinyUnlockValueUiStyle int32

// List of Destiny.DestinyUnlockValueUIStyle
const (
	0__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "0"
	1__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "1"
	2__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "2"
	3__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "3"
	4__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "4"
	5__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "5"
	6__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "6"
	7__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "7"
	8__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "8"
	9__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "9"
	10__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "10"
	11__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "11"
	12__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "12"
	13__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "13"
	14__DestinyDestinyUnlockValueUiStyle DestinyDestinyUnlockValueUiStyle = "14"
)
