/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type GroupsV2MembershipOption int32

// List of GroupsV2.MembershipOption
const (
	0__GroupsV2MembershipOption GroupsV2MembershipOption = "0"
	1__GroupsV2MembershipOption GroupsV2MembershipOption = "1"
	2__GroupsV2MembershipOption GroupsV2MembershipOption = "2"
)
