/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type GroupsV2GroupDateRange int32

// List of GroupsV2.GroupDateRange
const (
	_0__GroupsV2GroupDateRange GroupsV2GroupDateRange = 0
	_1__GroupsV2GroupDateRange GroupsV2GroupDateRange = 1
	_2__GroupsV2GroupDateRange GroupsV2GroupDateRange = 2
	_3__GroupsV2GroupDateRange GroupsV2GroupDateRange = 3
	_4__GroupsV2GroupDateRange GroupsV2GroupDateRange = 4
)
