/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Data related to your progress on the current season's artifact that is the same across characters.
type AllOfDestinyComponentsProfilesDestinyProfileProgressionComponentSeasonalArtifact struct {
	ArtifactHash int32 `json:"artifactHash,omitempty"`
	PointProgression *DestinyDestinyProgression `json:"pointProgression,omitempty"`
	PointsAcquired int32 `json:"pointsAcquired,omitempty"`
	PowerBonusProgression *DestinyDestinyProgression `json:"powerBonusProgression,omitempty"`
	PowerBonus int32 `json:"powerBonus,omitempty"`
}
