/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyStatCategory : At last, stats have categories. Use this for whatever purpose you might wish.
type DestinyDestinyStatCategory int32

// List of Destiny.DestinyStatCategory
const (
	0__DestinyDestinyStatCategory DestinyDestinyStatCategory = "0"
	1__DestinyDestinyStatCategory DestinyDestinyStatCategory = "1"
	2__DestinyDestinyStatCategory DestinyDestinyStatCategory = "2"
	3__DestinyDestinyStatCategory DestinyDestinyStatCategory = "3"
)
