/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Defines a single subscription: permission to send emails for a specific, focused subject (generally timeboxed, such as for a specific release of a product or feature).
type UserEmailSubscriptionDefinition struct {
	// The unique identifier for this subscription.
	Name string `json:"name,omitempty"`
	// A dictionary of localized text for the EMail Opt-in setting, keyed by the locale.
	Localization map[string]UserEMailSettingSubscriptionLocalization `json:"localization,omitempty"`
	// The bitflag value for this subscription. Should be a unique power of two value.
	Value int64 `json:"value,omitempty"`
}
