/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDefinitionsSocialDestinySocialCommendationNodeDefinition struct {
	DisplayProperties *DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition `json:"displayProperties,omitempty"`
	// The color associated with this group of commendations.
	Color *AllOfDestinyDefinitionsSocialDestinySocialCommendationNodeDefinitionColor `json:"color,omitempty"`
	ParentCommendationNodeHash int32 `json:"parentCommendationNodeHash,omitempty"`
	// A list of hashes that map to child commendation nodes. Only the root commendations node is expected to have child nodes.
	ChildCommendationNodeHashes []int32 `json:"childCommendationNodeHashes,omitempty"`
	// A list of hashes that map to child commendations.
	ChildCommendationHashes []int32 `json:"childCommendationHashes,omitempty"`
	// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
	Hash int32 `json:"hash,omitempty"`
	// The index of the entity as it was found in the investment tables.
	Index int32 `json:"index,omitempty"`
	// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
	Redacted bool `json:"redacted,omitempty"`
}
