/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDestinyRecordToastStyle int32

// List of Destiny.DestinyRecordToastStyle
const (
	_0__DestinyDestinyRecordToastStyle DestinyDestinyRecordToastStyle = 0
	_1__DestinyDestinyRecordToastStyle DestinyDestinyRecordToastStyle = 1
	_2__DestinyDestinyRecordToastStyle DestinyDestinyRecordToastStyle = 2
	_3__DestinyDestinyRecordToastStyle DestinyDestinyRecordToastStyle = 3
	_4__DestinyDestinyRecordToastStyle DestinyDestinyRecordToastStyle = 4
	_5__DestinyDestinyRecordToastStyle DestinyDestinyRecordToastStyle = 5
	_6__DestinyDestinyRecordToastStyle DestinyDestinyRecordToastStyle = 6
	_7__DestinyDestinyRecordToastStyle DestinyDestinyRecordToastStyle = 7
	_8__DestinyDestinyRecordToastStyle DestinyDestinyRecordToastStyle = 8
	_9__DestinyDestinyRecordToastStyle DestinyDestinyRecordToastStyle = 9
)
