/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyComponentsRecordsDestinyRecordComponent struct {
	State int32 `json:"state,omitempty"`
	Objectives []DestinyQuestsDestinyObjectiveProgress `json:"objectives,omitempty"`
	IntervalObjectives []DestinyQuestsDestinyObjectiveProgress `json:"intervalObjectives,omitempty"`
	IntervalsRedeemedCount int32 `json:"intervalsRedeemedCount,omitempty"`
	// If available, this is the number of times this record has been completed. For example, the number of times a seal title has been gilded.
	CompletedCount int32 `json:"completedCount,omitempty"`
	// If available, a list that describes which reward rewards should be shown (true) or hidden (false). This property is for regular record rewards, and not for interval objective rewards.
	RewardVisibilty []bool `json:"rewardVisibilty,omitempty"`
}
