/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDestinyActivityNavPointType int32

// List of Destiny.DestinyActivityNavPointType
const (
	_0__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 0
	_1__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 1
	_2__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 2
	_3__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 3
	_4__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 4
	_5__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 5
	_6__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 6
	_7__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 7
	_8__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 8
	_9__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 9
	_10__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 10
	_11__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 11
	_12__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 12
	_13__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 13
	_14__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 14
	_15__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 15
	_16__DestinyDestinyActivityNavPointType DestinyDestinyActivityNavPointType = 16
)
