/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ApplicationsSeries struct {
	// Collection of samples with time and value.
	Datapoints []ApplicationsDatapoint `json:"datapoints,omitempty"`
	// Target to which to datapoints apply.
	Target string `json:"target,omitempty"`
}
