/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyHistoricalStatsDestinyPlayer struct {
	// Details about the player as they are known in game (platform display name, Destiny emblem)
	DestinyUserInfo *AllOfDestinyHistoricalStatsDestinyPlayerDestinyUserInfo `json:"destinyUserInfo,omitempty"`
	// Class of the character if applicable and available.
	CharacterClass string `json:"characterClass,omitempty"`
	ClassHash int32 `json:"classHash,omitempty"`
	RaceHash int32 `json:"raceHash,omitempty"`
	GenderHash int32 `json:"genderHash,omitempty"`
	// Level of the character if available. Zero if it is not available.
	CharacterLevel int32 `json:"characterLevel,omitempty"`
	// Light Level of the character if available. Zero if it is not available.
	LightLevel int32 `json:"lightLevel,omitempty"`
	// Details about the player as they are known on BungieNet. This will be undefined if the player has marked their credential private, or does not have a BungieNet account.
	BungieNetUserInfo *AllOfDestinyHistoricalStatsDestinyPlayerBungieNetUserInfo `json:"bungieNetUserInfo,omitempty"`
	// Current clan name for the player. This value may be null or an empty string if the user does not have a clan.
	ClanName string `json:"clanName,omitempty"`
	// Current clan tag for the player. This value may be null or an empty string if the user does not have a clan.
	ClanTag string `json:"clanTag,omitempty"`
	// If we know the emblem's hash, this can be used to look up the player's emblem at the time of a match when receiving PGCR data, or otherwise their currently equipped emblem (if we are able to obtain it).
	EmblemHash int32 `json:"emblemHash,omitempty"`
}
