/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
import (
	"time"
)

// Items can have objectives and progression. When you request this block, you will obtain information about any Objectives and progression tied to this item.
type DestinyEntitiesItemsDestinyItemObjectivesComponent struct {
	// If the item has a hard association with objectives, your progress on them will be defined here.   Objectives are our standard way to describe a series of tasks that have to be completed for a reward.
	Objectives []DestinyQuestsDestinyObjectiveProgress `json:"objectives,omitempty"`
	// I may regret naming it this way - but this represents when an item has an objective that doesn't serve a beneficial purpose, but rather is used for \"flavor\" or additional information. For instance, when Emblems track specific stats, those stats are represented as Objectives on the item.
	FlavorObjective *AllOfDestinyEntitiesItemsDestinyItemObjectivesComponentFlavorObjective `json:"flavorObjective,omitempty"`
	// If we have any information on when these objectives were completed, this will be the date of that completion. This won't be on many items, but could be interesting for some items that do store this information.
	DateCompleted time.Time `json:"dateCompleted,omitempty"`
}
