/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyProgressionRewardItemState : Represents the different states a progression reward item can be in.
type DestinyDestinyProgressionRewardItemState int32

// List of Destiny.DestinyProgressionRewardItemState
const (
	0__DestinyDestinyProgressionRewardItemState DestinyDestinyProgressionRewardItemState = "0"
	1__DestinyDestinyProgressionRewardItemState DestinyDestinyProgressionRewardItemState = "1"
	2__DestinyDestinyProgressionRewardItemState DestinyDestinyProgressionRewardItemState = "2"
	4__DestinyDestinyProgressionRewardItemState DestinyDestinyProgressionRewardItemState = "4"
	8__DestinyDestinyProgressionRewardItemState DestinyDestinyProgressionRewardItemState = "8"
)
