/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// These properties are an attempt to categorize talent node steps by certain common properties. See the related enumerations for the type of properties being categorized.
type DestinyDefinitionsDestinyTalentNodeStepGroups struct {
	WeaponPerformance int32 `json:"weaponPerformance,omitempty"`
	ImpactEffects int32 `json:"impactEffects,omitempty"`
	GuardianAttributes int32 `json:"guardianAttributes,omitempty"`
	LightAbilities int32 `json:"lightAbilities,omitempty"`
	DamageTypes int32 `json:"damageTypes,omitempty"`
}
