/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyPresentationNodeState : I know this doesn't look like a Flags Enumeration/bitmask right now, but I assure you it is. This is the possible states that a Presentation Node can be in, and it is almost certain that its potential states will increase in the future. So don't treat it like a straight up enumeration.
type DestinyDestinyPresentationNodeState int32

// List of Destiny.DestinyPresentationNodeState
const (
	0__DestinyDestinyPresentationNodeState DestinyDestinyPresentationNodeState = "0"
	1__DestinyDestinyPresentationNodeState DestinyDestinyPresentationNodeState = "1"
	2__DestinyDestinyPresentationNodeState DestinyDestinyPresentationNodeState = "2"
)
