/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyItemBindStatus int32

// List of Destiny.ItemBindStatus
const (
	_0__DestinyItemBindStatus DestinyItemBindStatus = 0
	_1__DestinyItemBindStatus DestinyItemBindStatus = 1
	_2__DestinyItemBindStatus DestinyItemBindStatus = 2
	_3__DestinyItemBindStatus DestinyItemBindStatus = 3
)
