/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinySocketPlugSources : Indicates how a socket is populated, and where you should look for valid plug data.   This is a flags enumeration/bitmask field, as you may have to look in multiple sources across multiple components for valid plugs.   For instance, a socket could have plugs that are sourced from its own definition, as well as plugs that are sourced from Character-scoped AND profile-scoped Plug Sets. Only by combining plug data for every indicated source will you be able to know all of the plugs available for a socket.
type DestinySocketPlugSources int32

// List of Destiny.SocketPlugSources
const (
	_0__DestinySocketPlugSources DestinySocketPlugSources = 0
	_1__DestinySocketPlugSources DestinySocketPlugSources = 1
	_2__DestinySocketPlugSources DestinySocketPlugSources = 2
	_4__DestinySocketPlugSources DestinySocketPlugSources = 4
	_8__DestinySocketPlugSources DestinySocketPlugSources = 8
)
