/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyBucketCategory int32

// List of Destiny.BucketCategory
const (
	_0__DestinyBucketCategory DestinyBucketCategory = 0
	_1__DestinyBucketCategory DestinyBucketCategory = 1
	_2__DestinyBucketCategory DestinyBucketCategory = 2
	_3__DestinyBucketCategory DestinyBucketCategory = 3
	_4__DestinyBucketCategory DestinyBucketCategory = 4
)
