/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyVendorItemRefundPolicy : The action that happens when the user attempts to refund an item.
type DestinyDestinyVendorItemRefundPolicy int32

// List of Destiny.DestinyVendorItemRefundPolicy
const (
	0__DestinyDestinyVendorItemRefundPolicy DestinyDestinyVendorItemRefundPolicy = "0"
	1__DestinyDestinyVendorItemRefundPolicy DestinyDestinyVendorItemRefundPolicy = "1"
	2__DestinyDestinyVendorItemRefundPolicy DestinyDestinyVendorItemRefundPolicy = "2"
)
