/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type SocialFriendsPresenceOnlineStateFlags int32

// List of Social.Friends.PresenceOnlineStateFlags
const (
	0__SocialFriendsPresenceOnlineStateFlags SocialFriendsPresenceOnlineStateFlags = "0"
	1__SocialFriendsPresenceOnlineStateFlags SocialFriendsPresenceOnlineStateFlags = "1"
	2__SocialFriendsPresenceOnlineStateFlags SocialFriendsPresenceOnlineStateFlags = "2"
)
