/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyItemPerkVisibility : Indicates how a perk should be shown, or if it should be, in the game UI. Maybe useful for those of you trying to filter out internal-use-only perks (or for those of you trying to figure out what they do!)
type DestinyItemPerkVisibility int32

// List of Destiny.ItemPerkVisibility
const (
	_0__DestinyItemPerkVisibility DestinyItemPerkVisibility = 0
	_1__DestinyItemPerkVisibility DestinyItemPerkVisibility = 1
	_2__DestinyItemPerkVisibility DestinyItemPerkVisibility = 2
)
