/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDestinyPresentationNodeType int32

// List of Destiny.DestinyPresentationNodeType
const (
	0__DestinyDestinyPresentationNodeType DestinyDestinyPresentationNodeType = "0"
	1__DestinyDestinyPresentationNodeType DestinyDestinyPresentationNodeType = "1"
	2__DestinyDestinyPresentationNodeType DestinyDestinyPresentationNodeType = "2"
	3__DestinyDestinyPresentationNodeType DestinyDestinyPresentationNodeType = "3"
	4__DestinyDestinyPresentationNodeType DestinyDestinyPresentationNodeType = "4"
	5__DestinyDestinyPresentationNodeType DestinyDestinyPresentationNodeType = "5"
)
