/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDefinitionsDestinyObjectiveDisplayProperties struct {
	// The activity associated with this objective in the context of this item, if any.
	ActivityHash int32 `json:"activityHash,omitempty"`
	// If true, the game shows this objective on item preview screens.
	DisplayOnItemPreviewScreen bool `json:"displayOnItemPreviewScreen,omitempty"`
}
