/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ForumForumTopicsCategoryFiltersEnum int32

// List of Forum.ForumTopicsCategoryFiltersEnum
const (
	0__ForumForumTopicsCategoryFiltersEnum ForumForumTopicsCategoryFiltersEnum = "0"
	1__ForumForumTopicsCategoryFiltersEnum ForumForumTopicsCategoryFiltersEnum = "1"
	2__ForumForumTopicsCategoryFiltersEnum ForumForumTopicsCategoryFiltersEnum = "2"
	4__ForumForumTopicsCategoryFiltersEnum ForumForumTopicsCategoryFiltersEnum = "4"
	8__ForumForumTopicsCategoryFiltersEnum ForumForumTopicsCategoryFiltersEnum = "8"
	16__ForumForumTopicsCategoryFiltersEnum ForumForumTopicsCategoryFiltersEnum = "16"
	32__ForumForumTopicsCategoryFiltersEnum ForumForumTopicsCategoryFiltersEnum = "32"
	64__ForumForumTopicsCategoryFiltersEnum ForumForumTopicsCategoryFiltersEnum = "64"
	128__ForumForumTopicsCategoryFiltersEnum ForumForumTopicsCategoryFiltersEnum = "128"
)
