/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinySocketTypeActionType : Indicates the type of actions that can be performed
type DestinySocketTypeActionType int32

// List of Destiny.SocketTypeActionType
const (
	_0__DestinySocketTypeActionType DestinySocketTypeActionType = 0
	_1__DestinySocketTypeActionType DestinySocketTypeActionType = 1
	_2__DestinySocketTypeActionType DestinySocketTypeActionType = 2
)
