/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// If this item has related items in a \"Gear Set\", this will be non-null and the relationships defined herein.
type AllOfDestinyDefinitionsDestinyInventoryItemDefinitionGearset struct {
	// The maximum possible number of items that can be collected.
	TrackingValueMax int32 `json:"trackingValueMax,omitempty"`
	// The list of hashes for items in the gearset. Use them to look up DestinyInventoryItemDefinition entries for the items in the set.
	ItemList []int32 `json:"itemList,omitempty"`
}
