/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Defines the promotional text, images, and links to preview this season.
type DestinyDefinitionsSeasonsDestinySeasonPreviewDefinition struct {
	// A localized description of the season.
	Description string `json:"description,omitempty"`
	// A relative path to learn more about the season. Web browsers should be automatically redirected to the user's Bungie.net locale. For example: \"/SeasonOfTheChosen\" will redirect to \"/7/en/Seasons/SeasonOfTheChosen\" for English users.
	LinkPath string `json:"linkPath,omitempty"`
	// An optional link to a localized video, probably YouTube.
	VideoLink string `json:"videoLink,omitempty"`
	// A list of images to preview the seasonal content. Should have at least three to show.
	Images []DestinyDefinitionsSeasonsDestinySeasonPreviewImageDefinition `json:"images,omitempty"`
}
