/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyComponentsCraftablesDestinyCraftableSocketComponent struct {
	PlugSetHash int32 `json:"plugSetHash,omitempty"`
	// Unlock state for plugs in the socket plug set definition
	Plugs []DestinyComponentsCraftablesDestinyCraftableSocketPlugComponent `json:"plugs,omitempty"`
}
