/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDestinyTalentNodeState int32

// List of Destiny.DestinyTalentNodeState
const (
	_0__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 0
	_1__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 1
	_2__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 2
	_3__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 3
	_4__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 4
	_5__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 5
	_6__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 6
	_7__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 7
	_8__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 8
	_9__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 9
	_10__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 10
	_11__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 11
	_12__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 12
	_13__DestinyDestinyTalentNodeState DestinyDestinyTalentNodeState = 13
)
