/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ForumForumPostSortEnum int32

// List of Forum.ForumPostSortEnum
const (
	0__ForumForumPostSortEnum ForumForumPostSortEnum = "0"
	1__ForumForumPostSortEnum ForumForumPostSortEnum = "1"
)
