/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyItemLocation int32

// List of Destiny.ItemLocation
const (
	0__DestinyItemLocation DestinyItemLocation = "0"
	1__DestinyItemLocation DestinyItemLocation = "1"
	2__DestinyItemLocation DestinyItemLocation = "2"
	3__DestinyItemLocation DestinyItemLocation = "3"
	4__DestinyItemLocation DestinyItemLocation = "4"
)
