/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDamageType int32

// List of Destiny.DamageType
const (
	_0__DestinyDamageType DestinyDamageType = 0
	_1__DestinyDamageType DestinyDamageType = 1
	_2__DestinyDamageType DestinyDamageType = 2
	_3__DestinyDamageType DestinyDamageType = 3
	_4__DestinyDamageType DestinyDamageType = 4
	_5__DestinyDamageType DestinyDamageType = 5
	_6__DestinyDamageType DestinyDamageType = 6
	_7__DestinyDamageType DestinyDamageType = 7
)
