/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Localized text relevant to a given EMail setting in a given localization. Extra settings specifically for subscriptions.
type UserEMailSettingSubscriptionLocalization struct {
	UnknownUserDescription string `json:"unknownUserDescription,omitempty"`
	RegisteredUserDescription string `json:"registeredUserDescription,omitempty"`
	UnregisteredUserDescription string `json:"unregisteredUserDescription,omitempty"`
	UnknownUserActionText string `json:"unknownUserActionText,omitempty"`
	KnownUserActionText string `json:"knownUserActionText,omitempty"`
	Title string `json:"title,omitempty"`
	Description string `json:"description,omitempty"`
}
