/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDestinyGender int32

// List of Destiny.DestinyGender
const (
	0__DestinyDestinyGender DestinyDestinyGender = "0"
	1__DestinyDestinyGender DestinyDestinyGender = "1"
	2__DestinyDestinyGender DestinyDestinyGender = "2"
)
