/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ApplicationsApplicationStatus int32

// List of Applications.ApplicationStatus
const (
	0__ApplicationsApplicationStatus ApplicationsApplicationStatus = "0"
	1__ApplicationsApplicationStatus ApplicationsApplicationStatus = "1"
	2__ApplicationsApplicationStatus ApplicationsApplicationStatus = "2"
	3__ApplicationsApplicationStatus ApplicationsApplicationStatus = "3"
	4__ApplicationsApplicationStatus ApplicationsApplicationStatus = "4"
)
