/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyEntitiesItemsDestinyItemInstanceEnergy struct {
	// The type of energy for this item. Plugs that require Energy can only be inserted if they have the \"Any\" Energy Type or the matching energy type of this item. This is a reference to the DestinyEnergyTypeDefinition for the energy type, where you can find extended info about it.
	EnergyTypeHash int32 `json:"energyTypeHash,omitempty"`
	// This is the enum version of the Energy Type value, for convenience.
	EnergyType int32 `json:"energyType,omitempty"`
	// The total capacity of Energy that the item currently has, regardless of if it is currently being used.
	EnergyCapacity int32 `json:"energyCapacity,omitempty"`
	// The amount of Energy currently in use by inserted plugs.
	EnergyUsed int32 `json:"energyUsed,omitempty"`
	// The amount of energy still available for inserting new plugs.
	EnergyUnused int32 `json:"energyUnused,omitempty"`
}
