/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyObjectiveUiStyle : If the objective has a known UI label, this enumeration will represent it.
type DestinyDestinyObjectiveUiStyle int32

// List of Destiny.DestinyObjectiveUiStyle
const (
	0__DestinyDestinyObjectiveUiStyle DestinyDestinyObjectiveUiStyle = "0"
	1__DestinyDestinyObjectiveUiStyle DestinyDestinyObjectiveUiStyle = "1"
	2__DestinyDestinyObjectiveUiStyle DestinyDestinyObjectiveUiStyle = "2"
	3__DestinyDestinyObjectiveUiStyle DestinyDestinyObjectiveUiStyle = "3"
	4__DestinyDestinyObjectiveUiStyle DestinyDestinyObjectiveUiStyle = "4"
	5__DestinyDestinyObjectiveUiStyle DestinyDestinyObjectiveUiStyle = "5"
	6__DestinyDestinyObjectiveUiStyle DestinyDestinyObjectiveUiStyle = "6"
)
