/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyHistoricalStatsDestinyClanAggregateStat struct {
	// The id of the mode of stats (allPvp, allPvE, etc)
	Mode int32 `json:"mode,omitempty"`
	// The id of the stat
	StatId string `json:"statId,omitempty"`
	// Value of the stat for this player
	Value *AllOfDestinyHistoricalStatsDestinyClanAggregateStatValue `json:"value,omitempty"`
}
