/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyBucketCategory int32

// List of Destiny.BucketCategory
const (
	0__DestinyBucketCategory DestinyBucketCategory = "0"
	1__DestinyBucketCategory DestinyBucketCategory = "1"
	2__DestinyBucketCategory DestinyBucketCategory = "2"
	3__DestinyBucketCategory DestinyBucketCategory = "3"
	4__DestinyBucketCategory DestinyBucketCategory = "4"
)
