/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyVendorItemStatus int32

// List of Destiny.VendorItemStatus
const (
	_0__DestinyVendorItemStatus DestinyVendorItemStatus = 0
	_1__DestinyVendorItemStatus DestinyVendorItemStatus = 1
	_2__DestinyVendorItemStatus DestinyVendorItemStatus = 2
	_4__DestinyVendorItemStatus DestinyVendorItemStatus = 4
	_8__DestinyVendorItemStatus DestinyVendorItemStatus = 8
	_16__DestinyVendorItemStatus DestinyVendorItemStatus = 16
	_32__DestinyVendorItemStatus DestinyVendorItemStatus = 32
	_64__DestinyVendorItemStatus DestinyVendorItemStatus = 64
	_128__DestinyVendorItemStatus DestinyVendorItemStatus = 128
	_256__DestinyVendorItemStatus DestinyVendorItemStatus = 256
	_512__DestinyVendorItemStatus DestinyVendorItemStatus = 512
	_1024__DestinyVendorItemStatus DestinyVendorItemStatus = 1024
	_2048__DestinyVendorItemStatus DestinyVendorItemStatus = 2048
	_4096__DestinyVendorItemStatus DestinyVendorItemStatus = 4096
	_8192__DestinyVendorItemStatus DestinyVendorItemStatus = 8192
)
