/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyRequestsActionsDestinyInsertPlugsActionRequest struct {
	// Action token provided by the AwaGetActionToken API call.
	ActionToken string `json:"actionToken,omitempty"`
	// The instance ID of the item having a plug inserted. Only instanced items can have sockets.
	ItemInstanceId int64 `json:"itemInstanceId,omitempty"`
	// The plugs being inserted.
	Plug *AllOfDestinyRequestsActionsDestinyInsertPlugsActionRequestPlug `json:"plug,omitempty"`
	CharacterId int64 `json:"characterId,omitempty"`
	MembershipType int32 `json:"membershipType,omitempty"`
}
