/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
D2Client

// If this item can be rendered, this block will be non-null and will be populated with rendering information.
type AllOfDestinyDefinitionsDestinyInventoryItemDefinitionTranslationBlock struct {
	WeaponPatternIdentifier string `json:"weaponPatternIdentifier,omitempty"`
	WeaponPatternHash int32 `json:"weaponPatternHash,omitempty"`
	DefaultDyes []DestinyDyeReference `json:"defaultDyes,omitempty"`
	LockedDyes []DestinyDyeReference `json:"lockedDyes,omitempty"`
	CustomDyes []DestinyDyeReference `json:"customDyes,omitempty"`
	Arrangements []DestinyDefinitionsDestinyGearArtArrangementReference `json:"arrangements,omitempty"`
	HasGeometry bool `json:"hasGeometry,omitempty"`
}
