/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
import (
	"time"
)

// Defines a canonical \"Season\" of Destiny: a range of a few months where the game highlights certain challenges, provides new loot, has new Clan-related rewards and celebrates various seasonal events.
type DestinyDefinitionsSeasonsDestinySeasonDefinition struct {
	DisplayProperties *DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition `json:"displayProperties,omitempty"`
	BackgroundImagePath string `json:"backgroundImagePath,omitempty"`
	SeasonNumber int32 `json:"seasonNumber,omitempty"`
	StartDate time.Time `json:"startDate,omitempty"`
	EndDate time.Time `json:"endDate,omitempty"`
	SeasonPassHash int32 `json:"seasonPassHash,omitempty"`
	SeasonPassProgressionHash int32 `json:"seasonPassProgressionHash,omitempty"`
	ArtifactItemHash int32 `json:"artifactItemHash,omitempty"`
	SealPresentationNodeHash int32 `json:"sealPresentationNodeHash,omitempty"`
	SeasonalChallengesPresentationNodeHash int32 `json:"seasonalChallengesPresentationNodeHash,omitempty"`
	// Optional - Defines the promotional text, images, and links to preview this season.
	Preview *AllOfDestinyDefinitionsSeasonsDestinySeasonDefinitionPreview `json:"preview,omitempty"`
	// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
	Hash int32 `json:"hash,omitempty"`
	// The index of the entity as it was found in the investment tables.
	Index int32 `json:"index,omitempty"`
	// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
	Redacted bool `json:"redacted,omitempty"`
}
