/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyHistoricalStatsDefinitionsUnitType int32

// List of Destiny.HistoricalStats.Definitions.UnitType
const (
	_0__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 0
	_1__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 1
	_2__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 2
	_3__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 3
	_4__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 4
	_5__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 5
	_6__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 6
	_7__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 7
	_8__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 8
	_9__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 9
	_10__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 10
	_11__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 11
	_12__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 12
	_13__DestinyHistoricalStatsDefinitionsUnitType DestinyHistoricalStatsDefinitionsUnitType = 13
)
