/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type IgnoresIgnoreStatus int32

// List of Ignores.IgnoreStatus
const (
	_0__IgnoresIgnoreStatus IgnoresIgnoreStatus = 0
	_1__IgnoresIgnoreStatus IgnoresIgnoreStatus = 1
	_2__IgnoresIgnoreStatus IgnoresIgnoreStatus = 2
	_4__IgnoresIgnoreStatus IgnoresIgnoreStatus = 4
	_8__IgnoresIgnoreStatus IgnoresIgnoreStatus = 8
	_16__IgnoresIgnoreStatus IgnoresIgnoreStatus = 16
	_32__IgnoresIgnoreStatus IgnoresIgnoreStatus = 32
)
