/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyItemComponentSetOfuint32 struct {
	Instances *DictionaryComponentResponseOfuint32AndDestinyItemInstanceComponent `json:"instances,omitempty"`
	RenderData *DictionaryComponentResponseOfuint32AndDestinyItemRenderComponent `json:"renderData,omitempty"`
	Stats *DictionaryComponentResponseOfuint32AndDestinyItemStatsComponent `json:"stats,omitempty"`
	Sockets *DictionaryComponentResponseOfuint32AndDestinyItemSocketsComponent `json:"sockets,omitempty"`
	ReusablePlugs *DictionaryComponentResponseOfuint32AndDestinyItemReusablePlugsComponent `json:"reusablePlugs,omitempty"`
	PlugObjectives *DictionaryComponentResponseOfuint32AndDestinyItemPlugObjectivesComponent `json:"plugObjectives,omitempty"`
	TalentGrids *DictionaryComponentResponseOfuint32AndDestinyItemTalentGridComponent `json:"talentGrids,omitempty"`
	PlugStates *DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent `json:"plugStates,omitempty"`
	Objectives *DictionaryComponentResponseOfuint32AndDestinyItemObjectivesComponent `json:"objectives,omitempty"`
	Perks *DictionaryComponentResponseOfuint32AndDestinyItemPerksComponent `json:"perks,omitempty"`
}
