/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyArtifactsDestinyArtifactCharacterScoped struct {
	ArtifactHash int32 `json:"artifactHash,omitempty"`
	PointsUsed int32 `json:"pointsUsed,omitempty"`
	ResetCount int32 `json:"resetCount,omitempty"`
	Tiers []DestinyArtifactsDestinyArtifactTier `json:"tiers,omitempty"`
}
