/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Items can have Energy Capacity, and plugs can provide that capacity such as on a piece of Armor in Armor 2.0. This is how much \"Energy\" can be spent on activating plugs for this item.
type DestinyDefinitionsItemsDestinyEnergyCapacityEntry struct {
	// How much energy capacity this plug provides.
	CapacityValue int32 `json:"capacityValue,omitempty"`
	// Energy provided by a plug is always of a specific type - this is the hash identifier for the energy type for which it provides Capacity.
	EnergyTypeHash int32 `json:"energyTypeHash,omitempty"`
	// The Energy Type for this energy capacity, in enum form for easy use.
	EnergyType int32 `json:"energyType,omitempty"`
}
