/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
import (
	"time"
)

type FireteamFireteamMember struct {
	DestinyUserInfo *FireteamFireteamUserInfoCard `json:"destinyUserInfo,omitempty"`
	BungieNetUserInfo *UserUserInfoCard `json:"bungieNetUserInfo,omitempty"`
	CharacterId int64 `json:"characterId,omitempty"`
	DateJoined time.Time `json:"dateJoined,omitempty"`
	HasMicrophone bool `json:"hasMicrophone,omitempty"`
	LastPlatformInviteAttemptDate time.Time `json:"lastPlatformInviteAttemptDate,omitempty"`
	LastPlatformInviteAttemptResult int32 `json:"lastPlatformInviteAttemptResult,omitempty"`
}
