/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type UserOptInFlags int64

// List of User.OptInFlags
const (
	0__UserOptInFlags UserOptInFlags = "0"
	1__UserOptInFlags UserOptInFlags = "1"
	2__UserOptInFlags UserOptInFlags = "2"
	4__UserOptInFlags UserOptInFlags = "4"
	8__UserOptInFlags UserOptInFlags = "8"
	16__UserOptInFlags UserOptInFlags = "16"
	32__UserOptInFlags UserOptInFlags = "32"
	64__UserOptInFlags UserOptInFlags = "64"
	128__UserOptInFlags UserOptInFlags = "128"
	256__UserOptInFlags UserOptInFlags = "256"
)
