/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDestinySocketVisibility int32

// List of Destiny.DestinySocketVisibility
const (
	_0__DestinyDestinySocketVisibility DestinyDestinySocketVisibility = 0
	_1__DestinyDestinySocketVisibility DestinyDestinySocketVisibility = 1
	_2__DestinyDestinySocketVisibility DestinyDestinySocketVisibility = 2
	_3__DestinyDestinySocketVisibility DestinyDestinySocketVisibility = 3
)
