/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ContentModelsContentPreview struct {
	Name string `json:"name,omitempty"`
	Path string `json:"path,omitempty"`
	ItemInSet bool `json:"itemInSet,omitempty"`
	SetTag string `json:"setTag,omitempty"`
	SetNesting int32 `json:"setNesting,omitempty"`
	UseSetId int32 `json:"useSetId,omitempty"`
}
