/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Defines the thumbnail icon, high-res image, and video link for promotional images
type DestinyDefinitionsSeasonsDestinySeasonPreviewImageDefinition struct {
	// A thumbnail icon path to preview seasonal content, probably 480x270.
	ThumbnailImage string `json:"thumbnailImage,omitempty"`
	// An optional path to a high-resolution image, probably 1920x1080.
	HighResImage string `json:"highResImage,omitempty"`
}
