/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyEquipFailureReason : The reasons why an item cannot be equipped, if any. Many flags can be set, or \"None\" if
type DestinyEquipFailureReason int32

// List of Destiny.EquipFailureReason
const (
	0__DestinyEquipFailureReason DestinyEquipFailureReason = "0"
	1__DestinyEquipFailureReason DestinyEquipFailureReason = "1"
	2__DestinyEquipFailureReason DestinyEquipFailureReason = "2"
	4__DestinyEquipFailureReason DestinyEquipFailureReason = "4"
	8__DestinyEquipFailureReason DestinyEquipFailureReason = "8"
	16__DestinyEquipFailureReason DestinyEquipFailureReason = "16"
	32__DestinyEquipFailureReason DestinyEquipFailureReason = "32"
	64__DestinyEquipFailureReason DestinyEquipFailureReason = "64"
	128__DestinyEquipFailureReason DestinyEquipFailureReason = "128"
)
