/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDefinitionsDestinyActivityLoadoutRequirementSet struct {
	// The set of requirements that will be applied on the activity if this requirement set is active.
	Requirements []DestinyDefinitionsDestinyActivityLoadoutRequirement `json:"requirements,omitempty"`
}
