/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type UserEmailViewDefinitionSetting struct {
	// The identifier for this UI Setting, which can be used to relate it to custom strings or other data as desired.
	Name string `json:"name,omitempty"`
	// A dictionary of localized text for the EMail setting, keyed by the locale.
	Localization map[string]UserEMailSettingLocalization `json:"localization,omitempty"`
	// If true, this setting should be set by default if the user hasn't chosen whether it's set or cleared yet.
	SetByDefault bool `json:"setByDefault,omitempty"`
	// The OptInFlags value to set or clear if this setting is set or cleared in the UI. It is the aggregate of all underlying opt-in flags related to this setting.
	OptInAggregateValue int64 `json:"optInAggregateValue,omitempty"`
	// The subscriptions to show as children of this setting, if any.
	Subscriptions []UserEmailSubscriptionDefinition `json:"subscriptions,omitempty"`
}
