/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ApplicationsApiUsage struct {
	// Counts for on API calls made for the time range.
	ApiCalls []ApplicationsSeries `json:"apiCalls,omitempty"`
	// Instances of blocked requests or requests that crossed the warn threshold during the time range.
	ThrottledRequests []ApplicationsSeries `json:"throttledRequests,omitempty"`
}
