/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDefinitionsMilestonesDestinyMilestoneType : The type of milestone. Milestones can be Tutorials, one-time/triggered/non-repeating but not necessarily tutorials, or Repeating Milestones.
type DestinyDefinitionsMilestonesDestinyMilestoneType int32

// List of Destiny.Definitions.Milestones.DestinyMilestoneType
const (
	_0__DestinyDefinitionsMilestonesDestinyMilestoneType DestinyDefinitionsMilestonesDestinyMilestoneType = 0
	_1__DestinyDefinitionsMilestonesDestinyMilestoneType DestinyDefinitionsMilestonesDestinyMilestoneType = 1
	_2__DestinyDefinitionsMilestonesDestinyMilestoneType DestinyDefinitionsMilestonesDestinyMilestoneType = 2
	_3__DestinyDefinitionsMilestonesDestinyMilestoneType DestinyDefinitionsMilestonesDestinyMilestoneType = 3
	_4__DestinyDefinitionsMilestonesDestinyMilestoneType DestinyDefinitionsMilestonesDestinyMilestoneType = 4
	_5__DestinyDefinitionsMilestonesDestinyMilestoneType DestinyDefinitionsMilestonesDestinyMilestoneType = 5
)
