/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyAdvancedAwaInitializeResponse struct {
	// ID used to get the token. Present this ID to the user as it will identify this specific request on their device.
	CorrelationId string `json:"correlationId,omitempty"`
	// True if the PUSH message will only be sent to the device that made this request.
	SentToSelf bool `json:"sentToSelf,omitempty"`
}
