/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDestinyRace int32

// List of Destiny.DestinyRace
const (
	0__DestinyDestinyRace DestinyDestinyRace = "0"
	1__DestinyDestinyRace DestinyDestinyRace = "1"
	2__DestinyDestinyRace DestinyDestinyRace = "2"
	3__DestinyDestinyRace DestinyDestinyRace = "3"
)
