/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// The display properties of this bubble, so you don't have to look them up in a separate list anymore.
type AllOfDestinyDefinitionsDestinyBubbleDefinitionDisplayProperties struct {
	Description string `json:"description,omitempty"`
	Name string `json:"name,omitempty"`
	// Note that \"icon\" is sometimes misleading, and should be interpreted in the context of the entity. For instance, in Destiny 1 the DestinyRecordBookDefinition's icon was a big picture of a book.  But usually, it will be a small square image that you can use as... well, an icon.  They are currently represented as 96px x 96px images.
	Icon string `json:"icon,omitempty"`
	IconSequences []DestinyDefinitionsCommonDestinyIconSequenceDefinition `json:"iconSequences,omitempty"`
	// If this item has a high-res icon (at least for now, many things won't), then the path to that icon will be here.
	HighResIcon string `json:"highResIcon,omitempty"`
	HasIcon bool `json:"hasIcon,omitempty"`
}
