/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type UserHardLinkedUserMembership struct {
	MembershipType int32 `json:"membershipType,omitempty"`
	MembershipId int64 `json:"membershipId,omitempty"`
	CrossSaveOverriddenType int32 `json:"CrossSaveOverriddenType,omitempty"`
	CrossSaveOverriddenMembershipId int64 `json:"CrossSaveOverriddenMembershipId,omitempty"`
}
