/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Presentation nodes can be restricted by various requirements. This defines the rules of those requirements, and the message(s) to be shown if these requirements aren't met.
type DestinyDefinitionsPresentationDestinyPresentationNodeRequirementsBlock struct {
	// If this node is not accessible due to Entitlements (for instance, you don't own the required game expansion), this is the message to show.
	EntitlementUnavailableMessage string `json:"entitlementUnavailableMessage,omitempty"`
}
