/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ForumForumTopicsQuickDateEnum int32

// List of Forum.ForumTopicsQuickDateEnum
const (
	_0__ForumForumTopicsQuickDateEnum ForumForumTopicsQuickDateEnum = 0
	_1__ForumForumTopicsQuickDateEnum ForumForumTopicsQuickDateEnum = 1
	_2__ForumForumTopicsQuickDateEnum ForumForumTopicsQuickDateEnum = 2
	_3__ForumForumTopicsQuickDateEnum ForumForumTopicsQuickDateEnum = 3
	_4__ForumForumTopicsQuickDateEnum ForumForumTopicsQuickDateEnum = 4
)
