/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Information about objectives on Plugs for a given item. See the component's documentation for more info.  COMPONENT TYPE: ItemPlugObjectives
type AllOfDestinyResponsesDestinyItemResponsePlugObjectives struct {
	Data *DestinyComponentsItemsDestinyItemPlugObjectivesComponent `json:"data,omitempty"`
	Privacy int32 `json:"privacy,omitempty"`
	// If true, this component is disabled.
	Disabled bool `json:"disabled,omitempty"`
}
