/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// An old holdover from the original Armory, this was an attempt to group perks by functionality.  It is as yet unpopulated, and there will be quite a bit of work needed to restore it to its former working order.
type AllOfDestinyDefinitionsDestinySandboxPerkDefinitionPerkGroups struct {
	WeaponPerformance int32 `json:"weaponPerformance,omitempty"`
	ImpactEffects int32 `json:"impactEffects,omitempty"`
	GuardianAttributes int32 `json:"guardianAttributes,omitempty"`
	LightAbilities int32 `json:"lightAbilities,omitempty"`
	DamageTypes int32 `json:"damageTypes,omitempty"`
}
