/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ContentModelsContentPropertyDataTypeEnum int32

// List of Content.Models.ContentPropertyDataTypeEnum
const (
	0__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "0"
	1__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "1"
	2__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "2"
	3__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "3"
	4__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "4"
	5__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "5"
	6__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "6"
	7__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "7"
	8__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "8"
	9__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "9"
	10__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "10"
	11__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "11"
	12__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "12"
	13__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "13"
	14__ContentModelsContentPropertyDataTypeEnum ContentModelsContentPropertyDataTypeEnum = "14"
)
