/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type CommonModelsDestiny2CoreSettings struct {
	CollectionRootNode int32 `json:"collectionRootNode,omitempty"`
	BadgesRootNode int32 `json:"badgesRootNode,omitempty"`
	RecordsRootNode int32 `json:"recordsRootNode,omitempty"`
	MedalsRootNode int32 `json:"medalsRootNode,omitempty"`
	MetricsRootNode int32 `json:"metricsRootNode,omitempty"`
	ActiveTriumphsRootNodeHash int32 `json:"activeTriumphsRootNodeHash,omitempty"`
	ActiveSealsRootNodeHash int32 `json:"activeSealsRootNodeHash,omitempty"`
	LegacyTriumphsRootNodeHash int32 `json:"legacyTriumphsRootNodeHash,omitempty"`
	LegacySealsRootNodeHash int32 `json:"legacySealsRootNodeHash,omitempty"`
	MedalsRootNodeHash int32 `json:"medalsRootNodeHash,omitempty"`
	ExoticCatalystsRootNodeHash int32 `json:"exoticCatalystsRootNodeHash,omitempty"`
	LoreRootNodeHash int32 `json:"loreRootNodeHash,omitempty"`
	CraftingRootNodeHash int32 `json:"craftingRootNodeHash,omitempty"`
	LoadoutConstantsHash int32 `json:"loadoutConstantsHash,omitempty"`
	GuardianRankConstantsHash int32 `json:"guardianRankConstantsHash,omitempty"`
	GuardianRanksRootNodeHash int32 `json:"guardianRanksRootNodeHash,omitempty"`
	CurrentRankProgressionHashes []int32 `json:"currentRankProgressionHashes,omitempty"`
	InsertPlugFreeProtectedPlugItemHashes []int32 `json:"insertPlugFreeProtectedPlugItemHashes,omitempty"`
	InsertPlugFreeBlockedSocketTypeHashes []int32 `json:"insertPlugFreeBlockedSocketTypeHashes,omitempty"`
	UndiscoveredCollectibleImage string `json:"undiscoveredCollectibleImage,omitempty"`
	AmmoTypeHeavyIcon string `json:"ammoTypeHeavyIcon,omitempty"`
	AmmoTypeSpecialIcon string `json:"ammoTypeSpecialIcon,omitempty"`
	AmmoTypePrimaryIcon string `json:"ammoTypePrimaryIcon,omitempty"`
	CurrentSeasonalArtifactHash int32 `json:"currentSeasonalArtifactHash,omitempty"`
	CurrentSeasonHash int32 `json:"currentSeasonHash,omitempty"`
	SeasonalChallengesPresentationNodeHash int32 `json:"seasonalChallengesPresentationNodeHash,omitempty"`
	FutureSeasonHashes []int32 `json:"futureSeasonHashes,omitempty"`
	PastSeasonHashes []int32 `json:"pastSeasonHashes,omitempty"`
}
