/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDefinitionsPresentationDestinyScoredPresentationNodeBaseDefinition struct {
	MaxCategoryRecordScore int32 `json:"maxCategoryRecordScore,omitempty"`
	PresentationNodeType int32 `json:"presentationNodeType,omitempty"`
	TraitIds []string `json:"traitIds,omitempty"`
	TraitHashes []int32 `json:"traitHashes,omitempty"`
	// A quick reference to presentation nodes that have this node as a child. Presentation nodes can be parented under multiple parents.
	ParentNodeHashes []int32 `json:"parentNodeHashes,omitempty"`
	// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
	Hash int32 `json:"hash,omitempty"`
	// The index of the entity as it was found in the investment tables.
	Index int32 `json:"index,omitempty"`
	// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
	Redacted bool `json:"redacted,omitempty"`
}
