/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyPlugUiStyles : If the plug has a specific custom style, this enumeration will represent that style/those styles.
type DestinyPlugUiStyles int32

// List of Destiny.PlugUiStyles
const (
	_0__DestinyPlugUiStyles DestinyPlugUiStyles = 0
	_1__DestinyPlugUiStyles DestinyPlugUiStyles = 1
)
