/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyHistoricalStatsDefinitionsDestinyStatsGroupType : If the enum value is > 100, it is a \"special\" group that cannot be queried for directly (special cases apply to when they are returned, and are not relevant in general cases)
type DestinyHistoricalStatsDefinitionsDestinyStatsGroupType int32

// List of Destiny.HistoricalStats.Definitions.DestinyStatsGroupType
const (
	0__DestinyHistoricalStatsDefinitionsDestinyStatsGroupType DestinyHistoricalStatsDefinitionsDestinyStatsGroupType = "0"
	1__DestinyHistoricalStatsDefinitionsDestinyStatsGroupType DestinyHistoricalStatsDefinitionsDestinyStatsGroupType = "1"
	2__DestinyHistoricalStatsDefinitionsDestinyStatsGroupType DestinyHistoricalStatsDefinitionsDestinyStatsGroupType = "2"
	3__DestinyHistoricalStatsDefinitionsDestinyStatsGroupType DestinyHistoricalStatsDefinitionsDestinyStatsGroupType = "3"
	100__DestinyHistoricalStatsDefinitionsDestinyStatsGroupType DestinyHistoricalStatsDefinitionsDestinyStatsGroupType = "100"
	101__DestinyHistoricalStatsDefinitionsDestinyStatsGroupType DestinyHistoricalStatsDefinitionsDestinyStatsGroupType = "101"
	102__DestinyHistoricalStatsDefinitionsDestinyStatsGroupType DestinyHistoricalStatsDefinitionsDestinyStatsGroupType = "102"
	103__DestinyHistoricalStatsDefinitionsDestinyStatsGroupType DestinyHistoricalStatsDefinitionsDestinyStatsGroupType = "103"
	104__DestinyHistoricalStatsDefinitionsDestinyStatsGroupType DestinyHistoricalStatsDefinitionsDestinyStatsGroupType = "104"
)
