/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyHistoricalStatsDefinitionsDestinyHistoricalStatsDefinition struct {
	// Unique programmer friendly ID for this stat
	StatId string `json:"statId,omitempty"`
	// Statistic group
	Group int32 `json:"group,omitempty"`
	// Time periods the statistic covers
	PeriodTypes []int32 `json:"periodTypes,omitempty"`
	// Game modes where this statistic can be reported.
	Modes []int32 `json:"modes,omitempty"`
	// Category for the stat.
	Category int32 `json:"category,omitempty"`
	// Display name
	StatName string `json:"statName,omitempty"`
	// Display name abbreviated
	StatNameAbbr string `json:"statNameAbbr,omitempty"`
	// Description of a stat if applicable.
	StatDescription string `json:"statDescription,omitempty"`
	// Unit, if any, for the statistic
	UnitType int32 `json:"unitType,omitempty"`
	// Optional URI to an icon for the statistic
	IconImage string `json:"iconImage,omitempty"`
	// Optional icon for the statistic
	MergeMethod int32 `json:"mergeMethod,omitempty"`
	// Localized Unit Name for the stat.
	UnitLabel string `json:"unitLabel,omitempty"`
	// Weight assigned to this stat indicating its relative impressiveness.
	Weight int32 `json:"weight,omitempty"`
	// The tier associated with this medal - be it implicitly or explicitly.
	MedalTierHash int32 `json:"medalTierHash,omitempty"`
}
