/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// GroupsV2RuntimeGroupMemberType : The member levels used by all V2 Groups API. Individual group types use their own mappings in their native storage (general uses BnetDbGroupMemberType and D2 clans use ClanMemberLevel), but they are all translated to this in the runtime api. These runtime values should NEVER be stored anywhere, so the values can be changed as necessary.
type GroupsV2RuntimeGroupMemberType int32

// List of GroupsV2.RuntimeGroupMemberType
const (
	_0__GroupsV2RuntimeGroupMemberType GroupsV2RuntimeGroupMemberType = 0
	_1__GroupsV2RuntimeGroupMemberType GroupsV2RuntimeGroupMemberType = 1
	_2__GroupsV2RuntimeGroupMemberType GroupsV2RuntimeGroupMemberType = 2
	_3__GroupsV2RuntimeGroupMemberType GroupsV2RuntimeGroupMemberType = 3
	_4__GroupsV2RuntimeGroupMemberType GroupsV2RuntimeGroupMemberType = 4
	_5__GroupsV2RuntimeGroupMemberType GroupsV2RuntimeGroupMemberType = 5
)
