/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type GlobalAlertLevel int32

// List of GlobalAlertLevel
const (
	_0__GlobalAlertLevel GlobalAlertLevel = 0
	_1__GlobalAlertLevel GlobalAlertLevel = 1
	_2__GlobalAlertLevel GlobalAlertLevel = 2
	_3__GlobalAlertLevel GlobalAlertLevel = 3
)
