/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinySocketCategoryStyle : Represents the possible and known UI styles used by the game for rendering Socket Categories.
type DestinyDestinySocketCategoryStyle int32

// List of Destiny.DestinySocketCategoryStyle
const (
	_0__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = 0
	_1__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = 1
	_2__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = 2
	_3__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = 3
	_4__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = 4
	_5__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = 5
	_6__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = 6
	_7__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = 7
	_8__DestinyDestinySocketCategoryStyle DestinyDestinySocketCategoryStyle = 8
)
