/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyEnergyType : Represents the socket energy types for Armor 2.0, Ghosts 2.0, and Stasis subclasses.
type DestinyDestinyEnergyType int32

// List of Destiny.DestinyEnergyType
const (
	0__DestinyDestinyEnergyType DestinyDestinyEnergyType = "0"
	1__DestinyDestinyEnergyType DestinyDestinyEnergyType = "1"
	2__DestinyDestinyEnergyType DestinyDestinyEnergyType = "2"
	3__DestinyDestinyEnergyType DestinyDestinyEnergyType = "3"
	4__DestinyDestinyEnergyType DestinyDestinyEnergyType = "4"
	5__DestinyDestinyEnergyType DestinyDestinyEnergyType = "5"
	6__DestinyDestinyEnergyType DestinyDestinyEnergyType = "6"
)
