/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Information about the Reusable Plugs for sockets on an item. These are plugs that you can insert into the given socket regardless of if you actually own an instance of that plug: they are logic-driven plugs rather than inventory-driven.   These may need to be combined with Plug Set component data to get a full picture of available plugs on a given socket.   COMPONENT TYPE: ItemReusablePlugs
type AllOfDestinyResponsesDestinyItemResponseReusablePlugs struct {
	Data *DestinyComponentsItemsDestinyItemReusablePlugsComponent `json:"data,omitempty"`
	Privacy int32 `json:"privacy,omitempty"`
	// If true, this component is disabled.
	Disabled bool `json:"disabled,omitempty"`
}
