/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

// Very basic info about a user as returned by the Account server.
type UserUserMembership struct {
	// Type of the membership. Not necessarily the native type.
	MembershipType int32 `json:"membershipType,omitempty"`
	// Membership ID as they user is known in the Accounts service
	MembershipId int64 `json:"membershipId,omitempty"`
	// Display Name the player has chosen for themselves. The display name is optional when the data type is used as input to a platform API.
	DisplayName string `json:"displayName,omitempty"`
	// The bungie global display name, if set.
	BungieGlobalDisplayName string `json:"bungieGlobalDisplayName,omitempty"`
	// The bungie global display name code, if set.
	BungieGlobalDisplayNameCode int32 `json:"bungieGlobalDisplayNameCode,omitempty"`
}
