/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ForumsForumPostCategoryEnums int32

// List of Forums.ForumPostCategoryEnums
const (
	0__ForumsForumPostCategoryEnums ForumsForumPostCategoryEnums = "0"
	1__ForumsForumPostCategoryEnums ForumsForumPostCategoryEnums = "1"
	2__ForumsForumPostCategoryEnums ForumsForumPostCategoryEnums = "2"
	4__ForumsForumPostCategoryEnums ForumsForumPostCategoryEnums = "4"
	8__ForumsForumPostCategoryEnums ForumsForumPostCategoryEnums = "8"
	16__ForumsForumPostCategoryEnums ForumsForumPostCategoryEnums = "16"
	32__ForumsForumPostCategoryEnums ForumsForumPostCategoryEnums = "32"
	64__ForumsForumPostCategoryEnums ForumsForumPostCategoryEnums = "64"
	128__ForumsForumPostCategoryEnums ForumsForumPostCategoryEnums = "128"
	256__ForumsForumPostCategoryEnums ForumsForumPostCategoryEnums = "256"
	512__ForumsForumPostCategoryEnums ForumsForumPostCategoryEnums = "512"
	1024__ForumsForumPostCategoryEnums ForumsForumPostCategoryEnums = "1024"
)
