/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyComponentType : Represents the possible components that can be returned from Destiny \"Get\" calls such as GetProfile, GetCharacter, GetVendor etc...  When making one of these requests, you will pass one or more of these components as a comma separated list in the \"?components=\" querystring parameter. For instance, if you want baseline Profile data, Character Data, and character progressions, you would pass \"?components=Profiles,Characters,CharacterProgressions\" You may use either the numerical or string values.
type DestinyDestinyComponentType int32

// List of Destiny.DestinyComponentType
const (
	_0__DestinyDestinyComponentType DestinyDestinyComponentType = 0
	_100__DestinyDestinyComponentType DestinyDestinyComponentType = 100
	_101__DestinyDestinyComponentType DestinyDestinyComponentType = 101
	_102__DestinyDestinyComponentType DestinyDestinyComponentType = 102
	_103__DestinyDestinyComponentType DestinyDestinyComponentType = 103
	_104__DestinyDestinyComponentType DestinyDestinyComponentType = 104
	_105__DestinyDestinyComponentType DestinyDestinyComponentType = 105
	_200__DestinyDestinyComponentType DestinyDestinyComponentType = 200
	_201__DestinyDestinyComponentType DestinyDestinyComponentType = 201
	_202__DestinyDestinyComponentType DestinyDestinyComponentType = 202
	_203__DestinyDestinyComponentType DestinyDestinyComponentType = 203
	_204__DestinyDestinyComponentType DestinyDestinyComponentType = 204
	_205__DestinyDestinyComponentType DestinyDestinyComponentType = 205
	_206__DestinyDestinyComponentType DestinyDestinyComponentType = 206
	_300__DestinyDestinyComponentType DestinyDestinyComponentType = 300
	_301__DestinyDestinyComponentType DestinyDestinyComponentType = 301
	_302__DestinyDestinyComponentType DestinyDestinyComponentType = 302
	_303__DestinyDestinyComponentType DestinyDestinyComponentType = 303
	_304__DestinyDestinyComponentType DestinyDestinyComponentType = 304
	_305__DestinyDestinyComponentType DestinyDestinyComponentType = 305
	_306__DestinyDestinyComponentType DestinyDestinyComponentType = 306
	_307__DestinyDestinyComponentType DestinyDestinyComponentType = 307
	_308__DestinyDestinyComponentType DestinyDestinyComponentType = 308
	_309__DestinyDestinyComponentType DestinyDestinyComponentType = 309
	_310__DestinyDestinyComponentType DestinyDestinyComponentType = 310
	_400__DestinyDestinyComponentType DestinyDestinyComponentType = 400
	_401__DestinyDestinyComponentType DestinyDestinyComponentType = 401
	_402__DestinyDestinyComponentType DestinyDestinyComponentType = 402
	_500__DestinyDestinyComponentType DestinyDestinyComponentType = 500
	_600__DestinyDestinyComponentType DestinyDestinyComponentType = 600
	_700__DestinyDestinyComponentType DestinyDestinyComponentType = 700
	_800__DestinyDestinyComponentType DestinyDestinyComponentType = 800
	_900__DestinyDestinyComponentType DestinyDestinyComponentType = 900
	_1000__DestinyDestinyComponentType DestinyDestinyComponentType = 1000
	_1100__DestinyDestinyComponentType DestinyDestinyComponentType = 1100
	_1200__DestinyDestinyComponentType DestinyDestinyComponentType = 1200
	_1300__DestinyDestinyComponentType DestinyDestinyComponentType = 1300
	_1400__DestinyDestinyComponentType DestinyDestinyComponentType = 1400
)
