/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
import (
	"time"
)

type ForumPostResponse struct {
	LastReplyTimestamp time.Time `json:"lastReplyTimestamp,omitempty"`
	IsPinned bool `json:"IsPinned,omitempty"`
	UrlMediaType int32 `json:"urlMediaType,omitempty"`
	Thumbnail string `json:"thumbnail,omitempty"`
	Popularity int32 `json:"popularity,omitempty"`
	IsActive bool `json:"isActive,omitempty"`
	IsAnnouncement bool `json:"isAnnouncement,omitempty"`
	UserRating int32 `json:"userRating,omitempty"`
	UserHasRated bool `json:"userHasRated,omitempty"`
	UserHasMutedPost bool `json:"userHasMutedPost,omitempty"`
	LatestReplyPostId int64 `json:"latestReplyPostId,omitempty"`
	LatestReplyAuthorId int64 `json:"latestReplyAuthorId,omitempty"`
	IgnoreStatus *IgnoresIgnoreResponse `json:"ignoreStatus,omitempty"`
	Locale string `json:"locale,omitempty"`
}
