/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client
// DestinyDestinyProgressionScope : There are many Progressions in Destiny (think Character Level, or Reputation). These are the various \"Scopes\" of Progressions, which affect many things: * Where/if they are stored * How they are calculated * Where they can be used in other game logic
type DestinyDestinyProgressionScope int32

// List of Destiny.DestinyProgressionScope
const (
	0__DestinyDestinyProgressionScope DestinyDestinyProgressionScope = "0"
	1__DestinyDestinyProgressionScope DestinyDestinyProgressionScope = "1"
	2__DestinyDestinyProgressionScope DestinyDestinyProgressionScope = "2"
	3__DestinyDestinyProgressionScope DestinyDestinyProgressionScope = "3"
	4__DestinyDestinyProgressionScope DestinyDestinyProgressionScope = "4"
	5__DestinyDestinyProgressionScope DestinyDestinyProgressionScope = "5"
	6__DestinyDestinyProgressionScope DestinyDestinyProgressionScope = "6"
	7__DestinyDestinyProgressionScope DestinyDestinyProgressionScope = "7"
	8__DestinyDestinyProgressionScope DestinyDestinyProgressionScope = "8"
)
