/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDestinyClass int32

// List of Destiny.DestinyClass
const (
	_0__DestinyDestinyClass DestinyDestinyClass = 0
	_1__DestinyDestinyClass DestinyDestinyClass = 1
	_2__DestinyDestinyClass DestinyDestinyClass = 2
	_3__DestinyDestinyClass DestinyDestinyClass = 3
)
