/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type GroupsV2GroupApplicationResolveState int32

// List of GroupsV2.GroupApplicationResolveState
const (
	_0__GroupsV2GroupApplicationResolveState GroupsV2GroupApplicationResolveState = 0
	_1__GroupsV2GroupApplicationResolveState GroupsV2GroupApplicationResolveState = 1
	_2__GroupsV2GroupApplicationResolveState GroupsV2GroupApplicationResolveState = 2
	_3__GroupsV2GroupApplicationResolveState GroupsV2GroupApplicationResolveState = 3
)
