/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDestinyRace int32

// List of Destiny.DestinyRace
const (
	_0__DestinyDestinyRace DestinyDestinyRace = 0
	_1__DestinyDestinyRace DestinyDestinyRace = 1
	_2__DestinyDestinyRace DestinyDestinyRace = 2
	_3__DestinyDestinyRace DestinyDestinyRace = 3
)
