/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type DestinyDefinitionsGuardianRanksDestinyGuardianRankIconBackgroundsDefinition struct {
	BackgroundEmptyBorderedImagePath string `json:"backgroundEmptyBorderedImagePath,omitempty"`
	BackgroundEmptyBlueGradientBorderedImagePath string `json:"backgroundEmptyBlueGradientBorderedImagePath,omitempty"`
	BackgroundFilledBlueBorderedImagePath string `json:"backgroundFilledBlueBorderedImagePath,omitempty"`
	BackgroundFilledBlueGradientBorderedImagePath string `json:"backgroundFilledBlueGradientBorderedImagePath,omitempty"`
	BackgroundFilledBlueLowAlphaImagePath string `json:"backgroundFilledBlueLowAlphaImagePath,omitempty"`
	BackgroundFilledBlueMediumAlphaImagePath string `json:"backgroundFilledBlueMediumAlphaImagePath,omitempty"`
	BackgroundFilledGrayMediumAlphaBorderedImagePath string `json:"backgroundFilledGrayMediumAlphaBorderedImagePath,omitempty"`
	BackgroundFilledGrayHeavyAlphaBorderedImagePath string `json:"backgroundFilledGrayHeavyAlphaBorderedImagePath,omitempty"`
	BackgroundFilledWhiteMediumAlphaImagePath string `json:"backgroundFilledWhiteMediumAlphaImagePath,omitempty"`
	BackgroundFilledWhiteImagePath string `json:"backgroundFilledWhiteImagePath,omitempty"`
	BackgroundPlateWhiteImagePath string `json:"backgroundPlateWhiteImagePath,omitempty"`
	BackgroundPlateBlackImagePath string `json:"backgroundPlateBlackImagePath,omitempty"`
	BackgroundPlateBlackAlphaImagePath string `json:"backgroundPlateBlackAlphaImagePath,omitempty"`
}
