/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.18.0
 * Contact: support@bungie.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package D2Client

type ApplicationsDeveloperRole int32

// List of Applications.DeveloperRole
const (
	0__ApplicationsDeveloperRole ApplicationsDeveloperRole = "0"
	1__ApplicationsDeveloperRole ApplicationsDeveloperRole = "1"
	2__ApplicationsDeveloperRole ApplicationsDeveloperRole = "2"
)
